### ISSUE TITLE
Order of stories in the horizontal feed

### ISSUE THREAD

**Issue by subodhkolhe** [BulletIn-India/bulletin-android-client#2]
The latest story must come first in the order followed by the (latest -1). Currently the order is ascending and would want to have that order reversed so that the user sees the latest story first.

**Comment by rhoadster91** [comment]
This is already being done in newest first fashion. What you are probably referring to is this situation:
1. User opens the app
2. App starts fetching new stories
3. But app doesn't wait for new stories to fetch and directly starts showing already fetched stories
4. While showing existing stories, new story fetches are completed
These new stories get appended at the end of the list because it would not be a good user experience to switch stories while the user is still viewing them.
